#ifndef DLTREGISTRATION_GLOBAL_H
#define DLTREGISTRATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DLTREGISTRATION_LIBRARY)
#define DLTREGISTRATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#define DLTREGISTRATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DLTREGISTRATION_GLOBAL_H
